### ISSUE TITLE
Specify custom WORKDIR ? 

### ISSUE THREAD

**Issue by pcate-fls** [mserranom/bbrun#12]
First off, thank you for your work creating this tools, it's made debugging BB pipelines locally so much easier. 

I noticed that the working directory always seems to be `/ws` even if a different one is specified in the `Dockerfile` `WORKDIR`. Is there a command line flag or other option that can be setting to specific this?

I appreciate any help you can give me.

**Comment by mserranom** [comment]
You're right, it will use `/ws` regardless of the Dockerfile configuration.

We need to define the working directory at `docker run` time, since we need to mount the filesystem in the container. Potentially we could add a command line option to change the working directory, such as:

```
bbrun --work-dir /my_work_dir
```

Any thoughts?

**Comment by pcate-fls** [comment]
That looks good to me!

**Comment by mserranom** [comment]
Created PR, @pcate-fls feel free to have a look
